/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.dbscenarios1;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * ServerDefined generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SERVER DEFINED`")
public class ServerDefined implements Serializable {

    private Integer pkId;
    private String usernameCol;
    private Date curdateCol;
    private Time curtimeCol;
    private String charCol;
    private short userId;
    @Type(type = "DateTime")
    private LocalDateTime currentDateTime;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "\"SERVER DEFINED_PK ID_seq\"" , schema = "public", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`PK ID`", nullable = false, scale = 0, precision = 10)
    public Integer getPkId() {
        return this.pkId;
    }

    public void setPkId(Integer pkId) {
        this.pkId = pkId;
    }

    @Column(name = "`USERNAME COL`", nullable = true, length = 255)
    public String getUsernameCol() {
        return this.usernameCol;
    }

    public void setUsernameCol(String usernameCol) {
        this.usernameCol = usernameCol;
    }

    @Column(name = "`CURDATE COL`", nullable = false)
    public Date getCurdateCol() {
        return this.curdateCol;
    }

    public void setCurdateCol(Date curdateCol) {
        this.curdateCol = curdateCol;
    }

    @Column(name = "`CURTIME COL`", nullable = false)
    public Time getCurtimeCol() {
        return this.curtimeCol;
    }

    public void setCurtimeCol(Time curtimeCol) {
        this.curtimeCol = curtimeCol;
    }

    @Column(name = "`CHAR COL`", nullable = true, length = 1)
    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    @Column(name = "`USER ID`", nullable = false, scale = 0, precision = 5)
    public short getUserId() {
        return this.userId;
    }

    public void setUserId(short userId) {
        this.userId = userId;
    }

    @Column(name = "`CurrentDateTime`", nullable = true)
    public LocalDateTime getCurrentDateTime() {
        return this.currentDateTime;
    }

    public void setCurrentDateTime(LocalDateTime currentDateTime) {
        this.currentDateTime = currentDateTime;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ServerDefined)) return false;
        final ServerDefined serverDefined = (ServerDefined) o;
        return Objects.equals(getPkId(), serverDefined.getPkId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkId());
    }
}

