/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Blobtypes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`BLOBTYPES`")
public class Blobtypes implements Serializable {

    private Integer pkid;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobtype1;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobtype2;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobtype3;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobtype4;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobtype5;
    private Boolean booleancol;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`PKID`", nullable = false, scale = 0, precision = 10)
    public Integer getPkid() {
        return this.pkid;
    }

    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    @Column(name = "`BLOBTYPE1`", nullable = true)
    public byte[] getBlobtype1() {
        return this.blobtype1;
    }

    public void setBlobtype1(byte[] blobtype1) {
        this.blobtype1 = blobtype1;
    }

    @Column(name = "`BLOBTYPE2`", nullable = true)
    public byte[] getBlobtype2() {
        return this.blobtype2;
    }

    public void setBlobtype2(byte[] blobtype2) {
        this.blobtype2 = blobtype2;
    }

    @Column(name = "`BLOBTYPE3`", nullable = true)
    public byte[] getBlobtype3() {
        return this.blobtype3;
    }

    public void setBlobtype3(byte[] blobtype3) {
        this.blobtype3 = blobtype3;
    }

    @Column(name = "`BLOBTYPE4`", nullable = true)
    public byte[] getBlobtype4() {
        return this.blobtype4;
    }

    public void setBlobtype4(byte[] blobtype4) {
        this.blobtype4 = blobtype4;
    }

    @Column(name = "`BLOBTYPE5`", nullable = true)
    public byte[] getBlobtype5() {
        return this.blobtype5;
    }

    public void setBlobtype5(byte[] blobtype5) {
        this.blobtype5 = blobtype5;
    }

    @Column(name = "`BOOLEANCOL`", nullable = true)
    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Blobtypes)) return false;
        final Blobtypes blobtypes = (Blobtypes) o;
        return Objects.equals(getPkid(), blobtypes.getPkid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkid());
    }
}

