/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

public class HistPolicyInfoId implements Serializable {

    private String policyId;
    private Integer coverage;
    private Timestamp sysStart;
    private Timestamp sysEnd;
    private Timestamp createId;

    public String getPolicyId() {
        return this.policyId;
    }

    public void setPolicyId(String policyId) {
        this.policyId = policyId;
    }

    public Integer getCoverage() {
        return this.coverage;
    }

    public void setCoverage(Integer coverage) {
        this.coverage = coverage;
    }

    public Timestamp getSysStart() {
        return this.sysStart;
    }

    public void setSysStart(Timestamp sysStart) {
        this.sysStart = sysStart;
    }

    public Timestamp getSysEnd() {
        return this.sysEnd;
    }

    public void setSysEnd(Timestamp sysEnd) {
        this.sysEnd = sysEnd;
    }

    public Timestamp getCreateId() {
        return this.createId;
    }

    public void setCreateId(Timestamp createId) {
        this.createId = createId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof HistPolicyInfo)) return false;
        final HistPolicyInfo histPolicyInfo = (HistPolicyInfo) o;
        return Objects.equals(getPolicyId(), histPolicyInfo.getPolicyId()) &&
                Objects.equals(getCoverage(), histPolicyInfo.getCoverage()) &&
                Objects.equals(getSysStart(), histPolicyInfo.getSysStart()) &&
                Objects.equals(getSysEnd(), histPolicyInfo.getSysEnd()) &&
                Objects.equals(getCreateId(), histPolicyInfo.getCreateId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPolicyId(),
                getCoverage(),
                getSysStart(),
                getSysEnd(),
                getCreateId());
    }
}
