/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

public class PolicyInfoAttWithoutOverlapId implements Serializable {

    private String policyId;
    private Date busEnd;
    private Date busStart;

    public String getPolicyId() {
        return this.policyId;
    }

    public void setPolicyId(String policyId) {
        this.policyId = policyId;
    }

    public Date getBusEnd() {
        return this.busEnd;
    }

    public void setBusEnd(Date busEnd) {
        this.busEnd = busEnd;
    }

    public Date getBusStart() {
        return this.busStart;
    }

    public void setBusStart(Date busStart) {
        this.busStart = busStart;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PolicyInfoAttWithoutOverlap)) return false;
        final PolicyInfoAttWithoutOverlap policyInfoAttWithoutOverlap = (PolicyInfoAttWithoutOverlap) o;
        return Objects.equals(getPolicyId(), policyInfoAttWithoutOverlap.getPolicyId()) &&
                Objects.equals(getBusEnd(), policyInfoAttWithoutOverlap.getBusEnd()) &&
                Objects.equals(getBusStart(), policyInfoAttWithoutOverlap.getBusStart());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPolicyId(),
                getBusEnd(),
                getBusStart());
    }
}
