/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.sample;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

public class PolicyAttHistId implements Serializable {

    private String bank;
    private Timestamp busBegin;
    private Timestamp busEnd;
    private String client;
    private String type;
    private Integer pay;

    public String getBank() {
        return this.bank;
    }

    public void setBank(String bank) {
        this.bank = bank;
    }

    public Timestamp getBusBegin() {
        return this.busBegin;
    }

    public void setBusBegin(Timestamp busBegin) {
        this.busBegin = busBegin;
    }

    public Timestamp getBusEnd() {
        return this.busEnd;
    }

    public void setBusEnd(Timestamp busEnd) {
        this.busEnd = busEnd;
    }

    public String getClient() {
        return this.client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getPay() {
        return this.pay;
    }

    public void setPay(Integer pay) {
        this.pay = pay;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PolicyAttHist)) return false;
        final PolicyAttHist policyAttHist = (PolicyAttHist) o;
        return Objects.equals(getBank(), policyAttHist.getBank()) &&
                Objects.equals(getBusBegin(), policyAttHist.getBusBegin()) &&
                Objects.equals(getBusEnd(), policyAttHist.getBusEnd()) &&
                Objects.equals(getClient(), policyAttHist.getClient()) &&
                Objects.equals(getType(), policyAttHist.getType()) &&
                Objects.equals(getPay(), policyAttHist.getPay());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBank(),
                getBusBegin(),
                getBusEnd(),
                getClient(),
                getType(),
                getPay());
    }
}
