/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.sample.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureBonusIncResponseContent implements Serializable {


    @ColumnAlias("WORKDEPT")
    private String workdept;

    @ColumnAlias("EMPNO")
    private String empno;

    @ColumnAlias("BONUS")
    private Double bonus;

    public String getWorkdept() {
        return this.workdept;
    }

    public void setWorkdept(String workdept) {
        this.workdept = workdept;
    }

    public String getEmpno() {
        return this.empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    public Double getBonus() {
        return this.bonus;
    }

    public void setBonus(Double bonus) {
        this.bonus = bonus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureBonusIncResponseContent)) return false;
        final ProcedureBonusIncResponseContent procedureBonusIncResponseContent = (ProcedureBonusIncResponseContent) o;
        return Objects.equals(getWorkdept(), procedureBonusIncResponseContent.getWorkdept()) &&
                Objects.equals(getEmpno(), procedureBonusIncResponseContent.getEmpno()) &&
                Objects.equals(getBonus(), procedureBonusIncResponseContent.getBonus());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getWorkdept(),
                getEmpno(),
                getBonus());
    }
}
