/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.sample.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureBonusIncResponse implements Serializable {


    @ColumnAlias("content")
    private List<ProcedureBonusIncResponseContent> content;

    @ColumnAlias("P_DEPTSWITHOUTNEWBONUSES")
    private String pdeptswithoutnewbonuses;

    @ColumnAlias("P_COUNTDEPTSVIEWED")
    private Integer pcountdeptsviewed;

    @ColumnAlias("P_COUNTDEPTSBONUSCHANGED")
    private Integer pcountdeptsbonuschanged;

    @ColumnAlias("P_ERRORMSG")
    private String perrormsg;

    public List<ProcedureBonusIncResponseContent> getContent() {
        return this.content;
    }

    public void setContent(List<ProcedureBonusIncResponseContent> content) {
        this.content = content;
    }

    public String getPdeptswithoutnewbonuses() {
        return this.pdeptswithoutnewbonuses;
    }

    public void setPdeptswithoutnewbonuses(String pdeptswithoutnewbonuses) {
        this.pdeptswithoutnewbonuses = pdeptswithoutnewbonuses;
    }

    public Integer getPcountdeptsviewed() {
        return this.pcountdeptsviewed;
    }

    public void setPcountdeptsviewed(Integer pcountdeptsviewed) {
        this.pcountdeptsviewed = pcountdeptsviewed;
    }

    public Integer getPcountdeptsbonuschanged() {
        return this.pcountdeptsbonuschanged;
    }

    public void setPcountdeptsbonuschanged(Integer pcountdeptsbonuschanged) {
        this.pcountdeptsbonuschanged = pcountdeptsbonuschanged;
    }

    public String getPerrormsg() {
        return this.perrormsg;
    }

    public void setPerrormsg(String perrormsg) {
        this.perrormsg = perrormsg;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureBonusIncResponse)) return false;
        final ProcedureBonusIncResponse procedureBonusIncResponse = (ProcedureBonusIncResponse) o;
        return Objects.equals(getContent(), procedureBonusIncResponse.getContent()) &&
                Objects.equals(getPdeptswithoutnewbonuses(), procedureBonusIncResponse.getPdeptswithoutnewbonuses()) &&
                Objects.equals(getPcountdeptsviewed(), procedureBonusIncResponse.getPcountdeptsviewed()) &&
                Objects.equals(getPcountdeptsbonuschanged(), procedureBonusIncResponse.getPcountdeptsbonuschanged()) &&
                Objects.equals(getPerrormsg(), procedureBonusIncResponse.getPerrormsg());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContent(),
                getPdeptswithoutnewbonuses(),
                getPcountdeptsviewed(),
                getPcountdeptsbonuschanged(),
                getPerrormsg());
    }
}
