/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.dbscenarios.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureAllTypesUsingAliasResponse implements Serializable {


    @ColumnAlias("content")
    private List<ProcedureAllTypesUsingAliasResponseContent> content;

    public List<ProcedureAllTypesUsingAliasResponseContent> getContent() {
        return this.content;
    }

    public void setContent(List<ProcedureAllTypesUsingAliasResponseContent> content) {
        this.content = content;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureAllTypesUsingAliasResponse)) return false;
        final ProcedureAllTypesUsingAliasResponse procedureAllTypesUsingAliasResponse = (ProcedureAllTypesUsingAliasResponse) o;
        return Objects.equals(getContent(), procedureAllTypesUsingAliasResponse.getContent());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContent());
    }
}
