/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.dbscenarios.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureInoutResponse implements Serializable {


    @ColumnAlias("charcol")
    private String charcol;

    public String getCharcol() {
        return this.charcol;
    }

    public void setCharcol(String charcol) {
        this.charcol = charcol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureInoutResponse)) return false;
        final ProcedureInoutResponse procedureInoutResponse = (ProcedureInoutResponse) o;
        return Objects.equals(getCharcol(), procedureInoutResponse.getCharcol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCharcol());
    }
}
