/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.dbscenarios.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.List;
import java.util.Objects;

import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureAllTypesUsingAliasResponseContent implements Serializable {


    @ColumnAlias("PKCOLUMN")
    private Integer pkcolumn;

    @ColumnAlias("BYTE@COL")
    private Short byte_col;

    @ColumnAlias("SHORT COL")
    private Short shortCol;

    @ColumnAlias("LONG COL")
    private Long longCol;

    @ColumnAlias("DOUBLE COL")
    private BigDecimal doubleCol;

    @ColumnAlias("BIGINT COL")
    private Long bigintCol;

    @ColumnAlias("BIGDEC COL")
    private BigDecimal bigdecCol;

    @ColumnAlias("CHAR COL")
    private String charCol;

    @ColumnAlias("STRING COL")
    private String stringCol;

    @ColumnAlias("TEXT COL")
    private String textCol;

    @ColumnAlias("CLOB COL")
    private String clobCol;

    @ColumnAlias("DATE COL")
    private Date dateCol;

    @ColumnAlias("TIME COL")
    private Time timeCol;

    @ColumnAlias("DATETIME COL")
    private LocalDateTime datetimeCol;

    @ColumnAlias("TIMESTAMP COL")
    private Timestamp timestampCol;

    @ColumnAlias("BOOLEAN COL")
    private Boolean booleanCol;

    @JsonProperty(access = Access.READ_ONLY)
    @ColumnAlias("BLOB COL")
    private byte[] blobCol;

    public Integer getPkcolumn() {
        return this.pkcolumn;
    }

    public void setPkcolumn(Integer pkcolumn) {
        this.pkcolumn = pkcolumn;
    }

    public Short getByte_col() {
        return this.byte_col;
    }

    public void setByte_col(Short byte_col) {
        this.byte_col = byte_col;
    }

    public Short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(Short shortCol) {
        this.shortCol = shortCol;
    }

    public Long getLongCol() {
        return this.longCol;
    }

    public void setLongCol(Long longCol) {
        this.longCol = longCol;
    }

    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    public Long getBigintCol() {
        return this.bigintCol;
    }

    public void setBigintCol(Long bigintCol) {
        this.bigintCol = bigintCol;
    }

    public BigDecimal getBigdecCol() {
        return this.bigdecCol;
    }

    public void setBigdecCol(BigDecimal bigdecCol) {
        this.bigdecCol = bigdecCol;
    }

    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public String getTextCol() {
        return this.textCol;
    }

    public void setTextCol(String textCol) {
        this.textCol = textCol;
    }

    public String getClobCol() {
        return this.clobCol;
    }

    public void setClobCol(String clobCol) {
        this.clobCol = clobCol;
    }

    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    public Time getTimeCol() {
        return this.timeCol;
    }

    public void setTimeCol(Time timeCol) {
        this.timeCol = timeCol;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Timestamp getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(Timestamp timestampCol) {
        this.timestampCol = timestampCol;
    }

    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    public byte[] getBlobCol() {
        return this.blobCol;
    }

    public void setBlobCol(byte[] blobCol) {
        this.blobCol = blobCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureAllTypesUsingAliasResponseContent)) return false;
        final ProcedureAllTypesUsingAliasResponseContent procedureAllTypesUsingAliasResponseContent = (ProcedureAllTypesUsingAliasResponseContent) o;
        return Objects.equals(getPkcolumn(), procedureAllTypesUsingAliasResponseContent.getPkcolumn()) &&
                Objects.equals(getByte_col(), procedureAllTypesUsingAliasResponseContent.getByte_col()) &&
                Objects.equals(getShortCol(), procedureAllTypesUsingAliasResponseContent.getShortCol()) &&
                Objects.equals(getLongCol(), procedureAllTypesUsingAliasResponseContent.getLongCol()) &&
                Objects.equals(getDoubleCol(), procedureAllTypesUsingAliasResponseContent.getDoubleCol()) &&
                Objects.equals(getBigintCol(), procedureAllTypesUsingAliasResponseContent.getBigintCol()) &&
                Objects.equals(getBigdecCol(), procedureAllTypesUsingAliasResponseContent.getBigdecCol()) &&
                Objects.equals(getCharCol(), procedureAllTypesUsingAliasResponseContent.getCharCol()) &&
                Objects.equals(getStringCol(), procedureAllTypesUsingAliasResponseContent.getStringCol()) &&
                Objects.equals(getTextCol(), procedureAllTypesUsingAliasResponseContent.getTextCol()) &&
                Objects.equals(getClobCol(), procedureAllTypesUsingAliasResponseContent.getClobCol()) &&
                Objects.equals(getDateCol(), procedureAllTypesUsingAliasResponseContent.getDateCol()) &&
                Objects.equals(getTimeCol(), procedureAllTypesUsingAliasResponseContent.getTimeCol()) &&
                Objects.equals(getDatetimeCol(), procedureAllTypesUsingAliasResponseContent.getDatetimeCol()) &&
                Objects.equals(getTimestampCol(), procedureAllTypesUsingAliasResponseContent.getTimestampCol()) &&
                Objects.equals(getBooleanCol(), procedureAllTypesUsingAliasResponseContent.getBooleanCol()) &&
                Objects.equals(getBlobCol(), procedureAllTypesUsingAliasResponseContent.getBlobCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkcolumn(),
                getByte_col(),
                getShortCol(),
                getLongCol(),
                getDoubleCol(),
                getBigintCol(),
                getBigdecCol(),
                getCharCol(),
                getStringCol(),
                getTextCol(),
                getClobCol(),
                getDateCol(),
                getTimeCol(),
                getDatetimeCol(),
                getTimestampCol(),
                getBooleanCol(),
                getBlobCol());
    }
}
