/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.sample.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.hibernate.TypeMismatchException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.MultipartHttpServletRequest;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.DownloadResponse;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.runtime.util.WMRuntimeUtils;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.testing16thnov_production.sample.Userlogin;
import com.testing16thnov_production.sample.service.UserloginService;


/**
 * Controller object for domain model class Userlogin.
 * @see Userlogin
 */
@RestController("SAMPLE.UserloginController")
@Api(value = "UserloginController", description = "Exposes APIs to work with Userlogin resource.")
@RequestMapping("/SAMPLE/Userlogin")
public class UserloginController {

    private static final Logger LOGGER = LoggerFactory.getLogger(UserloginController.class);

    @Autowired
	@Qualifier("SAMPLE.UserloginService")
	private UserloginService userloginService;

	@ApiOperation(value = "Creates a new Userlogin instance.")
@RequestMapping(method = RequestMethod.POST, consumes = "multipart/form-data")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
public Userlogin createUserlogin(@RequestPart("wm_data_json") Userlogin userlogin, @RequestPart(value = "profilepic", required = false) MultipartFile _profilepic) {
		LOGGER.debug("Create Userlogin with information: {}" , userlogin);

    userlogin.setProfilepic(WMMultipartUtils.toByteArray(_profilepic));
		userlogin = userloginService.create(userlogin);
		LOGGER.debug("Created Userlogin with information: {}" , userlogin);

	    return userlogin;
	}

    @ApiOperation(value = "Returns the Userlogin instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Userlogin getUserlogin(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Getting Userlogin with id: {}" , id);

        Userlogin foundUserlogin = userloginService.getById(id);
        LOGGER.debug("Userlogin details with id: {}" , foundUserlogin);

        return foundUserlogin;
    }

    @ApiOperation(value = "Retrieves content for the given BLOB field in Userlogin instance" )
    @RequestMapping(value = "/{id}/content/{fieldName}", method = RequestMethod.GET, produces="application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public DownloadResponse getUserloginBLOBContent(@PathVariable("id") Integer id, @PathVariable("fieldName") String fieldName, HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse, @RequestParam(value="download", defaultValue = "false") boolean download) {

        LOGGER.debug("Retrieves content for the given BLOB field {} in Userlogin instance" , fieldName);

        if(!WMRuntimeUtils.isLob(Userlogin.class, fieldName)) {
            throw new TypeMismatchException("Given field " + fieldName + " is not a valid BLOB type");
        }
        Userlogin userlogin = userloginService.getById(id);

        return WMMultipartUtils.buildDownloadResponseForBlob(userlogin, fieldName, httpServletRequest, download);
    }

    @ApiOperation(value = "Updates the Userlogin instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.PUT)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Userlogin editUserlogin(@PathVariable("id") Integer id, @RequestBody Userlogin userlogin) throws EntityNotFoundException {
        LOGGER.debug("Editing Userlogin with id: {}" , userlogin.getUserid());

        userlogin.setUserid(id);
        userlogin = userloginService.update(userlogin);
        LOGGER.debug("Userlogin details with id: {}" , userlogin);

        return userlogin;
    }

    @ApiOperation(value = "Updates the Userlogin instance associated with the given id.This API should be used when Userlogin instance fields that require multipart data.") 
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.POST, consumes = {"multipart/form-data"})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Userlogin editUserlogin(@PathVariable("id") Integer id, MultipartHttpServletRequest multipartHttpServletRequest) throws EntityNotFoundException {
        Userlogin newUserlogin = WMMultipartUtils.toObject(multipartHttpServletRequest, Userlogin.class, "SAMPLE");
        newUserlogin.setUserid(id);

        Userlogin oldUserlogin = userloginService.getById(id);
        WMMultipartUtils.updateLobsContent(oldUserlogin, newUserlogin);
        LOGGER.debug("Updating Userlogin with information: {}" , newUserlogin);

        return userloginService.update(newUserlogin);
    }

    @ApiOperation(value = "Deletes the Userlogin instance associated with the given id.")
    @RequestMapping(value = "/{id:.+}", method = RequestMethod.DELETE)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteUserlogin(@PathVariable("id") Integer id) throws EntityNotFoundException {
        LOGGER.debug("Deleting Userlogin with id: {}" , id);

        Userlogin deletedUserlogin = userloginService.delete(id);

        return deletedUserlogin != null;
    }

    /**
     * @deprecated Use {@link #findUserlogins(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of Userlogin instances matching the search criteria.")
    @RequestMapping(value = "/search", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Userlogin> searchUserloginsByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering Userlogins list");
        return userloginService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Userlogin instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @RequestMapping(method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Userlogin> findUserlogins(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Userlogins list");
        return userloginService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of Userlogin instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @RequestMapping(value="/filter", method = RequestMethod.POST, consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<Userlogin> filterUserlogins(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering Userlogins list");
        return userloginService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
    @RequestMapping(value = "/export/{exportType}", method = {RequestMethod.GET,  RequestMethod.POST}, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportUserlogins(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return userloginService.export(exportType, query, pageable);
    }

	@ApiOperation(value = "Returns the total count of Userlogin instances matching the optional query (q) request param. If query string is too big to fit in GET request's query param, use POST method with application/x-www-form-urlencoded format.")
	@RequestMapping(value = "/count", method = {RequestMethod.GET, RequestMethod.POST})
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countUserlogins( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting Userlogins");
		return userloginService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@RequestMapping(value = "/aggregations", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getUserloginAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return userloginService.getAggregatedValues(aggregationInfo, pageable);
    }


    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service UserloginService instance
	 */
	protected void setUserloginService(UserloginService service) {
		this.userloginService = service;
	}

}

