/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing16thnov_production.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

import com.testing16thnov_production.dbscenarios.models.procedure.*;

@Service
public class DbscenariosProcedureExecutorServiceImpl implements DbscenariosProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(DbscenariosProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("dbscenariosWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;

    @Transactional(value = "dbscenariosTransactionManager")
    @Override
    public ProcedureAllTypesUsingAliasResponse executeProcedure_AllTypesUsingAlias() {
        Map params = new HashMap(0);


        return procedureExecutor.executeNamedProcedure("Procedure_AllTypesUsingAlias", params, ProcedureAllTypesUsingAliasResponse.class);
    }

    @Transactional(value = "dbscenariosTransactionManager")
    @Override
    public ProcedureInoutResponse executeProcedure_INOUT(String charcol) {
        Map params = new HashMap(1);

        params.put("charcol", charcol);

        return procedureExecutor.executeNamedProcedure("Procedure_INOUT", params, ProcedureInoutResponse.class);
    }

}


