/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing16thnov_production.db123__.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.util.List;
import java.util.Objects;

import org.joda.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureOnlyInResponseContent implements Serializable {


    @ColumnAlias("ASSIGNED ID")
    private Integer assignedId;

    @ColumnAlias("BYTE COL")
    private Byte byteCol;

    @ColumnAlias("SHORT COL")
    private Short shortCol;

    @ColumnAlias("INT COL")
    private Integer intCol;

    @ColumnAlias("FLOAT COL")
    private Double floatCol;

    @ColumnAlias("LONG COL")
    private Long longCol;

    @ColumnAlias("DOUBLE COL")
    private BigDecimal doubleCol;

    @ColumnAlias("BIGINT COL")
    private BigInteger bigintCol;

    @ColumnAlias("BIGDEC COL")
    private BigDecimal bigdecCol;

    @ColumnAlias("CHAR COL")
    private String charCol;

    @ColumnAlias("STRING COL")
    private String stringCol;

    @ColumnAlias("TEXT COL")
    private String textCol;

    @ColumnAlias("CLOB COL")
    private String clobCol;

    @ColumnAlias("DATE COL")
    private Date dateCol;

    @ColumnAlias("DATETIME COL")
    private LocalDateTime datetimeCol;

    @ColumnAlias("TIME COL")
    private Time timeCol;

    @ColumnAlias("TIMESTAMP COL")
    private LocalDateTime timestampCol;

    @ColumnAlias("BOOLEAN COL")
    private Boolean booleanCol;

    @JsonProperty(access = Access.READ_ONLY)
    @ColumnAlias("BLOB COL")
    private byte[] blobCol;

    public Integer getAssignedId() {
        return this.assignedId;
    }

    public void setAssignedId(Integer assignedId) {
        this.assignedId = assignedId;
    }

    public Byte getByteCol() {
        return this.byteCol;
    }

    public void setByteCol(Byte byteCol) {
        this.byteCol = byteCol;
    }

    public Short getShortCol() {
        return this.shortCol;
    }

    public void setShortCol(Short shortCol) {
        this.shortCol = shortCol;
    }

    public Integer getIntCol() {
        return this.intCol;
    }

    public void setIntCol(Integer intCol) {
        this.intCol = intCol;
    }

    public Double getFloatCol() {
        return this.floatCol;
    }

    public void setFloatCol(Double floatCol) {
        this.floatCol = floatCol;
    }

    public Long getLongCol() {
        return this.longCol;
    }

    public void setLongCol(Long longCol) {
        this.longCol = longCol;
    }

    public BigDecimal getDoubleCol() {
        return this.doubleCol;
    }

    public void setDoubleCol(BigDecimal doubleCol) {
        this.doubleCol = doubleCol;
    }

    public BigInteger getBigintCol() {
        return this.bigintCol;
    }

    public void setBigintCol(BigInteger bigintCol) {
        this.bigintCol = bigintCol;
    }

    public BigDecimal getBigdecCol() {
        return this.bigdecCol;
    }

    public void setBigdecCol(BigDecimal bigdecCol) {
        this.bigdecCol = bigdecCol;
    }

    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    public String getStringCol() {
        return this.stringCol;
    }

    public void setStringCol(String stringCol) {
        this.stringCol = stringCol;
    }

    public String getTextCol() {
        return this.textCol;
    }

    public void setTextCol(String textCol) {
        this.textCol = textCol;
    }

    public String getClobCol() {
        return this.clobCol;
    }

    public void setClobCol(String clobCol) {
        this.clobCol = clobCol;
    }

    public Date getDateCol() {
        return this.dateCol;
    }

    public void setDateCol(Date dateCol) {
        this.dateCol = dateCol;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Time getTimeCol() {
        return this.timeCol;
    }

    public void setTimeCol(Time timeCol) {
        this.timeCol = timeCol;
    }

    public LocalDateTime getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(LocalDateTime timestampCol) {
        this.timestampCol = timestampCol;
    }

    public Boolean getBooleanCol() {
        return this.booleanCol;
    }

    public void setBooleanCol(Boolean booleanCol) {
        this.booleanCol = booleanCol;
    }

    public byte[] getBlobCol() {
        return this.blobCol;
    }

    public void setBlobCol(byte[] blobCol) {
        this.blobCol = blobCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureOnlyInResponseContent)) return false;
        final ProcedureOnlyInResponseContent procedureOnlyInResponseContent = (ProcedureOnlyInResponseContent) o;
        return Objects.equals(getAssignedId(), procedureOnlyInResponseContent.getAssignedId()) &&
                Objects.equals(getByteCol(), procedureOnlyInResponseContent.getByteCol()) &&
                Objects.equals(getShortCol(), procedureOnlyInResponseContent.getShortCol()) &&
                Objects.equals(getIntCol(), procedureOnlyInResponseContent.getIntCol()) &&
                Objects.equals(getFloatCol(), procedureOnlyInResponseContent.getFloatCol()) &&
                Objects.equals(getLongCol(), procedureOnlyInResponseContent.getLongCol()) &&
                Objects.equals(getDoubleCol(), procedureOnlyInResponseContent.getDoubleCol()) &&
                Objects.equals(getBigintCol(), procedureOnlyInResponseContent.getBigintCol()) &&
                Objects.equals(getBigdecCol(), procedureOnlyInResponseContent.getBigdecCol()) &&
                Objects.equals(getCharCol(), procedureOnlyInResponseContent.getCharCol()) &&
                Objects.equals(getStringCol(), procedureOnlyInResponseContent.getStringCol()) &&
                Objects.equals(getTextCol(), procedureOnlyInResponseContent.getTextCol()) &&
                Objects.equals(getClobCol(), procedureOnlyInResponseContent.getClobCol()) &&
                Objects.equals(getDateCol(), procedureOnlyInResponseContent.getDateCol()) &&
                Objects.equals(getDatetimeCol(), procedureOnlyInResponseContent.getDatetimeCol()) &&
                Objects.equals(getTimeCol(), procedureOnlyInResponseContent.getTimeCol()) &&
                Objects.equals(getTimestampCol(), procedureOnlyInResponseContent.getTimestampCol()) &&
                Objects.equals(getBooleanCol(), procedureOnlyInResponseContent.getBooleanCol()) &&
                Objects.equals(getBlobCol(), procedureOnlyInResponseContent.getBlobCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAssignedId(),
                getByteCol(),
                getShortCol(),
                getIntCol(),
                getFloatCol(),
                getLongCol(),
                getDoubleCol(),
                getBigintCol(),
                getBigdecCol(),
                getCharCol(),
                getStringCol(),
                getTextCol(),
                getClobCol(),
                getDateCol(),
                getDatetimeCol(),
                getTimeCol(),
                getTimestampCol(),
                getBooleanCol(),
                getBlobCol());
    }
}
