/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing16thnov_production.sample.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

import com.testing16thnov_production.sample.models.procedure.*;

@Service
public class SAMPLEProcedureExecutorServiceImpl implements SAMPLEProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SAMPLEProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("SAMPLEWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;

    @Transactional(value = "SAMPLETransactionManager")
    @Override
    public ProcedureBonusIncResponse executeProcedure_BonusInc(Integer pbonusfactor, Integer pbonusmaxsumfordept) {
        Map params = new HashMap(6);

        params.put("P_BONUSFACTOR", pbonusfactor);
        params.put("P_BONUSMAXSUMFORDEPT", pbonusmaxsumfordept);

        return procedureExecutor.executeNamedProcedure("Procedure_BonusInc", params, ProcedureBonusIncResponse.class);
    }

}


